create table public.leads (
  id bigint generated by default as identity primary key,
  name text not null default '',
  tg_username text not null default '',
  phone text not null default '',
  email text not null default '',
  address text not null default '',
  kind text not null default 'request'
    constraint leads_kind_check check (kind in ('lead', 'request')),
  source text not null default 'site_order',
  request_type text not null default '',
  product text not null default '',
  status text not null default 'new'
    constraint leads_status_check check (status in ('lead', 'new', 'in_progress', 'link_sent', 'paid', 'closed')),
  notes text not null default '',
  unread integer not null default 0
    constraint leads_unread_check check (unread in (0, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  sender text not null
    constraint messages_sender_check check (sender in ('client', 'maria', 'system')),
  text text not null,
  created_at timestamptz not null default now()
);

create index leads_updated_at_idx on public.leads(updated_at desc);
create index messages_lead_id_idx on public.messages(lead_id, id);

alter table public.leads enable row level security;
alter table public.messages enable row level security;

revoke all on table public.leads, public.messages from anon, authenticated;
grant all on table public.leads, public.messages to service_role;
grant usage, select on sequence public.leads_id_seq, public.messages_id_seq to service_role;

comment on table public.leads is 'Private CRM leads for Maria Flora';
comment on table public.messages is 'Private CRM conversation history';
